# Base image
FROM node:18.16.1 AS base

# Set working directory
WORKDIR /server

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Stage for production build
FROM base AS production

# Set environment variable for production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# Install production dependencies only
RUN npm ci --only=production

# Build the app for production (if needed)
# If your project has a build step (like for a frontend app), uncomment the next line
# RUN npm run build

# Make sure the entrypoint script is executable
RUN chmod +x /src/entrypoint.sh

# Set the entrypoint
ENTRYPOINT [ "/src/entrypoint.sh" ]

# Stage for development environment
FROM base AS development

# Set environment variable for development
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Install all dependencies (including devDependencies)
RUN npm install

# Make sure the entrypoint script is executable
RUN chmod +x /src/entrypoint.sh

# Set the entrypoint
ENTRYPOINT [ "/src/entrypoint.sh" ]

# Expose the application port
EXPOSE 5000
